---
- name: Hello World!
  hosts: all
  tasks:
  - name: Hello World!
    shell: echo "Hi! Tower is working!"

  - name: Hostname
    ansible.builtin.debug:
      msg: "My hostname is {{ ansible_host }}"
